version: '3.8'

services:
  web:
    image: ${DOCKER_REGISTRY:-localhost}/swarm-demo-app:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VERSION=${VERSION:-1.0.0}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    volumes:
      - app-logs:/app/logs

networks:
  app-network:
    driver: overlay

volumes:
  app-logs: 